### ISSUE TITLE
large negative gsw_t_freezing anomaly at large absolute salinity

### ISSUE THREAD

**Issue by chrisdane** [TEOS-10/GSW-R#54] opened 2022-01-06 08:44 UTC
Hi

At 0 dbar, `gsw_t_freezing` yields a large negative in situ freezing temperature anomaly in a specific range of large absolute salinity (SA):
```r
SA <- seq(762.5, 765.5, l=100) # g/kg
tf <- gsw::gsw_t_freezing(SA=SA, p=0) # °C
plot(SA, tf)
```
<img src=https://user-images.githubusercontent.com/26486859/148353175-441f6bd3-1eed-48fc-92e7-b1dd4cd24d27.png alt="tfreeze_vs_SA_762-766_g_kg" width="500"/>

At 1000 dbar, this anomaly shifts to larger SA:

<img src=https://user-images.githubusercontent.com/26486859/148353374-a94d504d-076f-45e7-b6db-ab841c3986d2.png alt="tfreeze_vs_SA_806-809_g_kg" width="500"/>

I am aware that these salinity ranges have nothing to do with real oceanography but I was wondering if this is a bug in the function or not.

Thanks and cheers,
Chris

```r
packageDescription("gsw")
Version: 1.0-6
Date/Publication: 2021-07-07 17:30:02 UTC
Built: R 4.1.1; x86_64-pc-linux-gnu; 2021-11-01 15:06:00 UTC; unix
```

**Comment by PaulMBarker** [comment] 2022-01-06 09:32
All of TEOS-10 is valid with the Absolute Salinity varying between 0 and 42 g/kg. The features you describe are well and truly outside of this range. Thus this is not a bug.

Paul.

**Comment by chrisdane** [comment] 2022-01-06 10:09
Does that mean that the function is not defined for SA > 42 g/kg? I think it is but with the exception I showed above?

**Comment by PaulMBarker** [comment] 2022-01-06 10:57
The function is not valid above for SA > 42 g/kg.

I suggest you read the manual http://www.teos-10.org/pubs/TEOS-10_Manual.pdf, particularly Section 2.6 and Figure 3 on page 16.

Paul.

**Comment by richardsc** [comment] 2022-01-06 18:02
Hi @chrisdane 

@PaulMBarker is 100% correct that you should consider the GSW functions as accurate only within the ranges of 0 <= SA <=42. So, this isn't really a bug because the documentation states you shouldn't use them so far out of range (this came up recently in another discussion about whether to actually *limit* the functions to that range, in TEOS-10/GSW-C#48, and it was decided not to).

Paul would know the details, but I expect what you are seeing is the effect of a polynomial fit being taken way outside of its intended range. For interest, I plotted up the results for freezing temperature using GSW and the old UNESCO fomulae. The UNESCO one does something more sensible for large salinity, but again it's only valid to the same range so I wouldn't use it either.

![image](https://user-images.githubusercontent.com/233584/148428794-499627d0-68f6-4d81-a4a5-20e0681dedf2.png)

**Comment by dankelley** [comment] 2022-01-06 19:12
In R, documentation is produced semi-automatically, and it's possible to create "templates".  For Absolute Salinity, we presently have
```R
#' @param SA Absolute Salinity [ g/kg ]
```
which sets how this parameter is defined in the help pages.  

This use of templates is convenient because if I change that to read e.g.
```R
#' @param SA Absolute Salinity [ g/kg ]. The range of validity is from 0 to 42 g/kg, as explained in Section 2.6 of [reference].
```
and do similarly for `CT` and `p`, then the help pages for any R functions that have these quantities as parameters will be updated to be more helpful.

Unless @richardsc objects, I'll do this on the weekend.  It's been 6 months since gsw-R was updated on CRAN, but I don't really think this documentation change is sufficient to go through that process again.  (Clark may think differently, of course.)

**Comment by richardsc** [comment] 2022-01-06 19:40
@dankelley I do not object to updating the template.

I would however propose that we close this issue as being "addressed". If more discussion is warranted, it can be re-opened.

**Closed by richardsc** 2022-01-06 19:40 UTC
